/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databarang;
/**
 *
 * @author fadil
 */
public class data extends javax.swing.JFrame {
    DefaultComboBoxModel mdl = new DefaultComboBoxModel();
    int baris =0;
    static Object [] kolom = {"id_barang","nama_barang","harga","id_kategori"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    /**
     * Creates new form Barang
     */
    public data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        ktg_brg = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fharga = new javax.swing.JTextField();
        tsimpan = new javax.swing.JButton();
        ttambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tedit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_brg = new javax.swing.JTable();
        fcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("/ BARANG /");

        fnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnamaActionPerformed(evt);
            }
        });

        ktg_brg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ktg_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktg_brgActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kategori Barang");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga Barang");

        tsimpan.setBackground(new java.awt.Color(255, 255, 255));
        tsimpan.setForeground(new java.awt.Color(0, 0, 0));
        tsimpan.setText("simpan");
        tsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsimpanActionPerformed(evt);
            }
        });

        ttambah.setBackground(new java.awt.Color(255, 255, 255));
        ttambah.setForeground(new java.awt.Color(0, 0, 0));
        ttambah.setText("tambah");
        ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttambahActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(255, 255, 255));
        hapus.setForeground(new java.awt.Color(0, 0, 0));
        hapus.setText("hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tedit.setBackground(new java.awt.Color(255, 255, 255));
        tedit.setForeground(new java.awt.Color(0, 0, 0));
        tedit.setText("edit");
        tedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teditActionPerformed(evt);
            }
        });

        tbl_brg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_brg);

        bcari.setBackground(new java.awt.Color(255, 255, 255));
        bcari.setForeground(new java.awt.Color(0, 0, 0));
        bcari.setText("cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID_Barang");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Barang");

        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ktg_brg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fnama)
                            .addComponent(fharga)
                            .addComponent(fid)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ttambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tedit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bcari)
                    .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ktg_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttambah)
                    .addComponent(tsimpan)
                    .addComponent(tedit)
                    .addComponent(hapus))
                .addContainerGap())
        );

        jMenu1.setForeground(new java.awt.Color(0, 102, 255));
        jMenu1.setText("kategori");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ktg_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktg_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktg_brgActionPerformed

    private void ttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttambahActionPerformed
        if(fid.getText().isEmpty()||fnama.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap isi data dengan lengkap",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(fharga.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap isi data dengan lengkap",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            databarang obj = new databarang();
        String Cid_ktg = ktg_brg.getSelectedItem().toString();
        String id_barang = fid.getText();
        String namabarang = fnama.getText();
        String buy = fharga.getText();
        
        String[] pisahKategori = Cid_ktg.split("-");
        String id_Kategori = pisahKategori[0];
        String namaKategori = pisahKategori[1];
        
        if(id_barang.isEmpty()){
            JOptionPane.showMessageDialog(this, "id kategori harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(namabarang.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama kategori harus diisi",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
            obj.TambahDataBarang(id_barang, namabarang, buy, id_Kategori);
            tbl.addRow(new Object[]{id_barang, namabarang, buy, id_Kategori});
            tbl_brg.setModel(tbl);
            fid.setText("");
            fnama.setText("");
            fharga.setText("");
        }
        }
    }//GEN-LAST:event_ttambahActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        kategori menu = new kategori();
        this.setVisible(false);
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        databarang obj2 = new databarang();
        //get data combobox
        String [] ListKategori = obj2.getListKategori();
        for(int i=0; i<ListKategori.length; i++){
            mdl.addElement(ListKategori[i]);
        }
        ktg_brg.setModel(mdl);
        
        databarang obj = new databarang();
        //get data tabel
        String [][] data = obj.getDataBarang();
        for(int i=0; i<data.length; i++){
        tbl.addRow(new Object[]{data[i][0],data[i][1],data[i][2],data[i][3]});
    }
        tbl_brg.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        databarang obj1 = new databarang();
        
        String kataKunci = fcari.getText();
        tbl.getDataVector().removeAllElements();
        
        String [][] data = obj1.CariDataBarang(kataKunci);
        for(int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[]{data[i][0], data[i][1],data[i][2],data[i][3]});
        }
        tbl_brg.setModel(tbl);
        fcari.setText("");
    }//GEN-LAST:event_bcariActionPerformed

    private void tsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsimpanActionPerformed
        databarang obj1 = new databarang();
        String KategoriBuku = ktg_brg.getSelectedItem().toString();
        String idbarang = fid.getText();
        String namabarang = fnama.getText();
        String harga = fharga.getText();
        
        if(idbarang.isEmpty() || namabarang.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap edit data dengan benar",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);      
        }else if(harga.isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap edit data dengan benar",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        String[] pisahKategori = KategoriBuku.split("-");
        String KodeKategori = pisahKategori[0];
        String Kategori = pisahKategori[1];
        
        obj1.editBarang(idbarang, namabarang, harga, KodeKategori);
        tbl.getDataVector().removeAllElements();
        
        //get data tabel
        String [][] data = obj1.getDataBarang();
        for(int i=0; i<data.length; i++){
            tbl.addRow(new Object[]{data[i][0], data[i][1],data[i][2],data[i][3]});           
        }
        tbl_brg.setModel(tbl);
        
        JOptionPane.showMessageDialog(this, "Data berhasil diedit",
                    "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        fid.setEditable(true);
        fid.setText("");
        fnama.setText("");
        fharga.setText("");
        }
    }//GEN-LAST:event_tsimpanActionPerformed

    private void teditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teditActionPerformed
        databarang obj1 = new databarang();
        
        int Pilihbaris = tbl_brg.getSelectedRow();
        
        if(tbl_brg.isRowSelected(Pilihbaris)){
        String KodeBuku = tbl.getValueAt(Pilihbaris, 0).toString();
        String[][] data = obj1.getDataBarang(KodeBuku);        
        String nama_barang = data[0][1];
        String harga = data[0][2];
        String id_kategori = data[0][3];
        String nama_kategori = data[0][4];
        
        ktg_brg.setSelectedItem(id_kategori+"-"+nama_kategori);
        fid.setText(KodeBuku);
        fid.setEditable(false);
        fnama.setText(nama_barang);
        fharga.setText(harga);
        }else{
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_teditActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        databarang obj = new databarang();
        
        int Pilihbaris = tbl_brg.getSelectedRow();
        if(tbl_brg.isRowSelected(Pilihbaris)){
        String id_barang = tbl.getValueAt(Pilihbaris, 0).toString();
        
        obj.HapusDataBarang(id_barang);
        tbl.removeRow(Pilihbaris);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
                "Pesan Keonfirmasi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu",
                "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void fnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JTextField fcari;
    private javax.swing.JTextField fharga;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fnama;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> ktg_brg;
    private javax.swing.JTable tbl_brg;
    private javax.swing.JButton tedit;
    private javax.swing.JButton tsimpan;
    private javax.swing.JButton ttambah;
    // End of variables declaration//GEN-END:variables
}
