/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.databarang;
import model.trans_brg;
import model.user;
/**
 *
 * @author fadil
 */
public class transaksi extends javax.swing.JFrame {
int baris =0;
private String IDUser = user.getIDUser();
private String Telp = user.getTelp();
    static Object [] kolom = {"id barang","nama barang","harga"};
    static Object [] kolom2 = {"nama barang","harga","jumlah"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    DefaultTableModel tbl2 = new DefaultTableModel(kolom2, baris);
    ArrayList <Integer> takhir = new ArrayList<>();
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ttambah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_brg = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bbuy = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nm_brg = new javax.swing.JTextField();
        hrg = new javax.swing.JTextField();
        jml = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_keranjang = new javax.swing.JTable();
        t_akhir = new javax.swing.JLabel();
        fcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("-Daftar Barang-");

        ttambah.setBackground(new java.awt.Color(255, 255, 255));
        ttambah.setText("tambah");
        ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttambahActionPerformed(evt);
            }
        });

        tbl_brg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_brg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl_brgMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_brg);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("-Keranjang-");

        bbuy.setBackground(new java.awt.Color(255, 255, 255));
        bbuy.setText("beli");
        bbuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuyActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 255, 255));
        bhapus.setText("hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total : Rp.");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Barang");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah");

        nm_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_brgActionPerformed(evt);
            }
        });

        tbl_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_keranjang);

        t_akhir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        t_akhir.setForeground(new java.awt.Color(255, 255, 255));
        t_akhir.setText("jLabel7");

        cari.setBackground(new java.awt.Color(255, 255, 255));
        cari.setText("cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_akhir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbuy, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ttambah))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hrg)
                                    .addComponent(jml)
                                    .addComponent(nm_brg, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari)
                    .addComponent(fcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nm_brg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttambah)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbuy)
                    .addComponent(bhapus)
                    .addComponent(jLabel3)
                    .addComponent(t_akhir))
                .addContainerGap())
        );

        jMenu1.setForeground(new java.awt.Color(0, 102, 255));
        jMenu1.setText("profil");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu1MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nm_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm_brgActionPerformed

    private void ttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttambahActionPerformed
        if(nm_brg.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Harap pilih barang", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(jml.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Tentukan jumlah barang", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        trans_brg obj = new trans_brg();
        String SJumlah = jml.getText();       
        int Pilihbaris = tbl_brg.getSelectedRow();
        String id_brg = tbl.getValueAt(Pilihbaris, 0).toString();
        String [][] data = obj.getDataBarang(id_brg);
        String nama_barang = data[0][0];
        String harga = data[0][1];        
        tbl2.addRow(new Object[]{nama_barang,harga,SJumlah});
        tbl_keranjang.setModel(tbl2);
        int jmlKolom = tbl_keranjang.getColumnCount();
        int brs = tbl_keranjang.getRowCount() - 1;
        int r = brs;
        String krj [][] = new String[brs + 5][jmlKolom];        
        for(int c=0; c<jmlKolom-1; c++){
            krj[r][c]= data[0][c];            
        }
        krj[r][2]= SJumlah;
        trans_brg.setJumlah(SJumlah, harga);
        takhir.add(obj.hitung_total());
        
        //hitung total
        int total = 0;    
        for(int i=0; i<takhir.size();i++){
        total += takhir.get(i);
        }
        String Total = Integer.toString(total);
        t_akhir.setText(Total);
        
        //clear form
        nm_brg.setText("");
        hrg.setText("");
        jml.setText("");
        }
    }//GEN-LAST:event_ttambahActionPerformed

    private void jMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MousePressed

    }//GEN-LAST:event_jMenu1MousePressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        profil d = new profil();
        this.setVisible(false);
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        trans_brg obj = new trans_brg();
        //get data tabel
        String [][] data = obj.getBarang();
        for(int i=0; i<data.length; i++){
        tbl.addRow(new Object[]{data[i][0],data[i][1],data[i][2]});
    }
        tbl_brg.setModel(tbl);
        tbl_keranjang.setModel(tbl2);
        nm_brg.setEditable(false);
        hrg.setEditable(false);
        t_akhir.setText("0");
    }//GEN-LAST:event_formComponentShown

    private void tbl_brgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_brgMouseReleased
        trans_brg obj = new trans_brg();        
        int Pilihbaris = tbl_brg.getSelectedRow();
        String id_brg = tbl.getValueAt(Pilihbaris, 0).toString();
        String [][] data = obj.getDataBarang(id_brg);
        nm_brg.setText(data[0][0]);
        hrg.setText(data[0][1]);
    }//GEN-LAST:event_tbl_brgMouseReleased

    private void bbuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuyActionPerformed
        if(tbl_keranjang.getRowCount()==0){
        JOptionPane.showMessageDialog(this, "Harus ada barang yang dibeli", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else{
        trans_brg obj = new trans_brg();        
        int jmlKolom = tbl_keranjang.getColumnCount(); 
        int brs = tbl_keranjang.getRowCount() - 1;
        String total = t_akhir.getText();
        String krj [][] = new String[1000][jmlKolom];
        for(int r=0; r<=brs; r++){
            for(int c=0; c<jmlKolom; c++){ 
            krj[r][c]= tbl_keranjang.getValueAt(r, c).toString();  
        }
            String id_brg = obj.getID_Barang(krj[r][0], krj[r][1]);
            obj.keranjang(IDUser, id_brg, krj[r][2]);
        }
        JOptionPane.showMessageDialog(this, "Kode Pembayaran "+IDUser+Telp
                + "\nJumlah Yang Harus Dibayar Rp."+total, 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        t_akhir.setText("0");
        takhir.clear();
        tbl2.getDataVector().removeAllElements();
        tbl2.fireTableDataChanged();
        }
    }//GEN-LAST:event_bbuyActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int kol = tbl_keranjang.getSelectedRow();
        if(tbl_keranjang.getRowCount()==0){
        JOptionPane.showMessageDialog(this, "Harus ada barang yang dibeli", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }else if(tbl_keranjang.isRowSelected(kol)){        
        tbl2.removeRow(kol);
        takhir.remove(kol);
        int total = 0;
        for(int i=0; i<takhir.size(); i++){
            total += takhir.get(i);
        }
        String Total = Integer.toString(total);
        t_akhir.setText(Total);
        }else{
        JOptionPane.showMessageDialog(this, "Pilih barang yang ingin dihapus", 
        "Pesan Kesalahan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        databarang obj1 = new databarang();
        
        String kataKunci = fcari.getText();
        tbl.getDataVector().removeAllElements();
        
        String [][] data = obj1.CariDataBarang(kataKunci);
        for(int i=0; i<data.length; i++){
            int no = i + 1;
            tbl.addRow(new Object[]{data[i][0], data[i][1],data[i][2]});
        }
        tbl_brg.setModel(tbl);
        fcari.setText("");
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trans_brg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trans_brg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trans_brg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trans_brg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbuy;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton cari;
    private javax.swing.JTextField fcari;
    private javax.swing.JTextField hrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jml;
    private javax.swing.JTextField nm_brg;
    private javax.swing.JLabel t_akhir;
    private javax.swing.JTable tbl_brg;
    private javax.swing.JTable tbl_keranjang;
    private javax.swing.JButton ttambah;
    // End of variables declaration//GEN-END:variables
}
